Fix dimensions of psci_req_local_pwr_states
Wrong array size cause compilation error when using GCC 7.2:

lib/psci/psci_common.c: In function ‘psci_do_state_coordination’:
lib/psci/psci_common.c:220:27: error: array subscript is above array bounds [-Werror=array-bounds]
psci_req_local_pwr_states[pwrlvl - 1][cpu_idx] = req_pwr_state;

Signed-off-by: Bernhard Rosenkränzer <bero@lindev.ch>